### ISSUE TITLE
re-run CLA test for cpython pull-request after flag set, 

### ISSUE THREAD

**Issue by chadmiller-amzn** [python/the-knights-who-say-ni#139] opened 2018-03-27 22:04 UTC
This needs CLA-check run again.
https://github.com/python/cpython/pull/6122

I understand this bug tracker is for the code, and not the current state of pull-requests. The docs about where to ask do not say where to ask.

https://devguide.python.org/pullrequest/#licensing

"After signing the CLA, please wait at least one US business day and then check “Your Details” on b.p.o to see if your account has been marked as having signed the CLA (the delay is due to a person having to manually check your signed CLA). Once you have verified that your b.p.o account reflects your signing of the CLA, *you can either ask for the CLA check to be run again* or wait for it to be run automatically the next time you push changes to your PR."

**Comment by Mariatta** [comment] 2018-03-27 22:18
Thanks for the report. I'll close this as a duplicate of #110.
It is indeed a problem in our workflow.
We've discussed several options. The best solution is to perhaps have a webhook in the bpo that triggers the recheck after the CLA is signed, and that is something to be done in the bpo, not here.

**Comment by Mariatta** [comment] 2018-03-27 22:18
Duplicate of #110

**Closed** 2018-03-27 22:19 UTC
