### ISSUE TITLE
Have the-knights-who-say-ni recheck CLA-signed status

### ISSUE THREAD

**Issue by Mariatta** [python/the-knights-who-say-ni#110] opened 2017-04-18 18:52 UTC
Currently, after contributor signed the CLA, they would come back to the issue and write a comment like "I've signed the CLA".
After that, it becomes a manual work for one of the core devs to remove the `CLA not signed` label just so the status check can be triggered again.

Maybe it will be good if contributors could issue a command like `@the-knights-who-say-ni recheck` as a comment, and the bot can pick this up and automatically perform the status check again.

What do you think about this?

**Comment by berkerpeksag** [comment] 2017-04-19 06:15
+1 to the idea. `@the-knights-who-say-ni done` is also a common reply.

**Comment by brettcannon** [comment] 2017-04-19 21:59
Part of the problem is that the comment typically comes right after they have signed the CLA, so it would still not change the status as the fact that they signed would not have been recorded yet.

**Comment by Mariatta** [comment] 2017-04-20 02:26
Hmm that is a good point. Maybe the bot can reply with "Try again after 24 hours" 😁

**Comment by brettcannon** [comment] 2017-05-12 19:20
The other option is if we just rechecked after every comment or review comment. The worry there is if this won't blow out the 5,000 calls/hour we are restricted to (which is 1.3 calls/second).

Lastly, we could potentially run a daily [cron job](https://elements.heroku.com/addons/scheduler) which goes through all open PRs that are flagged as not having their PR signed and then check them. This solution is a bit more tied to our hosting solution, though (but I would expect any hosting platform would have some kind of similar support).

**Comment by brettcannon** [comment] 2017-06-24 00:45
I think a good solution to this might be to create a page that uses [reCAPTCHA](https://www.google.com/recaptcha/intro/) which lets people manually trigger the check. It can be linked to from either the comment or the Details link once #42 is implemented.

**Comment by merwok** [comment] 2018-04-06 16:47
In the meantime, I think it would be useful to change the bot message to explain that a Python dev will need to delete the label to cause a re-check.  I have seen a few messages where people wonder what they should do after they send their CLA.

**Comment by brettcannon** [comment] 2018-04-06 22:09
Thinking about this some more, I think if we can have Roundup send an HTTP POST request to the bot any time someone's CLA status changes, it can then get a list of all open issues with the `CLA not signed` label, look for any PRs for that person, and then change the label. Now to prevent forgeries there would need to be a shared secret between Roundup and the bot, otherwise the bot will simply have to turn around and immediately ask b.p.o to do an explicit validation (which is cheap considering this isn't a high traffic event so it might not be worth trying to coordinate a secret). Another cheap way to do this would to simply re-check all `CLA not signed`-labeled PRs and not worry about the wasted checks.

**Comment by brettcannon** [comment] 2018-04-06 22:10
@merwok I would accept a PR that added a message about that.

**Comment by merwok** [comment] 2018-04-09 14:39
PR opened!

**Comment by ned-deily** [comment] 2018-04-14 00:57
@brettcannon Did you want to close this issue?

**Comment by merwok** [comment] 2018-04-14 04:08
Ah I guess my PR description of «Useful until we fix #110» caused this

**Comment by brettcannon** [comment] 2018-04-24 23:51
I realize one trick with the "automatically check everything" option is we need to know what repos have the Ni bot activated to make sure we check them.

As for a link to trigger a re-check, https://github.com/Microsoft/vscode-python/pull/1475#issuecomment-384034230 shows how the Microsoft CLA bot does this.

**Closed** 2018-08-13 21:56 UTC
Labels: enhancement
